export const pricingTiers = [
  {
    id: "free",
    name: "Free Forever",
    subtitle: "Desktop Application",
    badge: "Most Popular",
    price: 0,
    priceMonthly: 0,
    description: "Download once. Use forever. No subscriptions.",
    features: [
      "✓ FREE desktop application download",
      "✓ Use with Ollama (100% free, runs locally)",
      "✓ OR bring your own API keys (OpenAI, Anthropic, Google)",
      "✓ All 19 automation tools included",
      "✓ Desktop + Browser + Database automation",
      "✓ Knowledge base & learning system",
      "✓ Unlimited automation runs",
      "✓ Windows 10/11 support",
      "✓ Community support",
    ],
    cta: "Download Free",
    ctaHref: "/download",
    popular: true,
    costNote: "FREE with Ollama, or ~$0.04/task with cloud LLMs",
  },
  {
    id: "byok",
    name: "Bring Your Own Keys",
    subtitle: "Pay-As-You-Go",
    badge: "Flexible",
    price: null,
    priceMonthly: null,
    customPrice: "~$0.04",
    customPriceUnit: "per task",
    description: "Use cloud LLMs with your own API keys",
    features: [
      "✓ Everything in Free Forever",
      "✓ Use OpenAI GPT-4, GPT-4o models",
      "✓ Use Anthropic Claude 3.5 Sonnet, Opus",
      "✓ Use Google Gemini 1.5 Pro/Flash",
      "✓ Intelligent provider routing",
      "✓ Real-time cost tracking",
      "✓ Token budgeting with alerts",
      "✓ 125x lower cost than traditional RPA",
      "✓ No markup - pay providers directly",
    ],
    cta: "Download Free",
    ctaHref: "/download",
    popular: false,
    costNote: "Average $0.04/task vs $5+ traditional methods",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    subtitle: "For Organizations",
    badge: "Custom Support",
    price: null,
    priceMonthly: null,
    description: "Premium support and custom features",
    features: [
      "✓ Everything included",
      "✓ Dedicated support team",
      "✓ Custom integration development",
      "✓ Priority bug fixes & features",
      "✓ SSO/SAML authentication",
      "✓ On-premise deployment assistance",
      "✓ 99.9% uptime SLA",
      "✓ Team training & onboarding",
      "✓ Custom tool development",
    ],
    cta: "Contact Sales",
    ctaHref: "/contact?plan=enterprise",
    popular: false,
    costNote: "Custom pricing for enterprise support",
  },
]

export type PricingTier = typeof pricingTiers[number]
