export const pricingTiers = [
  {
    id: "free",
    name: "Free",
    subtitle: "Community",
    badge: "Perfect for trying out",
    price: 0,
    priceMonthly: 0,
    description: "Get started with basic automation",
    features: [
      "100 automation runs/month",
      "Local Ollama LLM support",
      "Basic desktop automation",
      "Community support",
      "Single workspace",
    ],
    cta: "Download Free",
    ctaHref: "/download",
    popular: false,
  },
  {
    id: "pro",
    name: "Pro",
    subtitle: "Most Popular",
    badge: "MOST POPULAR",
    price: 10,
    priceMonthly: 20,
    originalPrice: 20,
    description: "Unlimited automation for professionals",
    features: [
      "Unlimited automation runs",
      "All LLM providers (OpenAI, Anthropic, Google, Ollama)",
      "Advanced desktop automation",
      "Browser automation (Playwright)",
      "Database & API integrations",
      "Priority email support",
      "5 workspaces",
      "Cost analytics & tracking",
      "Cloud sync (optional)",
    ],
    cta: "Start Pro Trial",
    ctaHref: "/signup?plan=pro",
    popular: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    subtitle: "For teams",
    badge: "Custom",
    price: null,
    priceMonthly: null,
    description: "Advanced features for organizations",
    features: [
      "Everything in Pro",
      "Unlimited workspaces",
      "SSO/SAML authentication",
      "Dedicated support",
      "Custom integrations",
      "On-premise deployment option",
      "SLA guarantee",
      "Training & onboarding",
    ],
    cta: "Contact Sales",
    ctaHref: "/contact?plan=enterprise",
    popular: false,
  },
]

export type PricingTier = typeof pricingTiers[number]
