export const pricingTiers = [
  {
    id: "free",
    name: "Free Tier",
    subtitle: "Get Started",
    badge: "Great for Testing",
    price: 0,
    priceMonthly: 0,
    description: "Perfect for trying out AI employees and workflows",
    features: [
      "✓ 10 hours automation/month",
      "✓ 20+ pre-built AI employees",
      "✓ Access to workflow marketplace",
      "✓ Basic support",
      "✓ Real-time ROI dashboard",
      "✓ Community forums",
      "✓ All desktop features included",
      "✓ Windows 10/11 support",
    ],
    cta: "Start Free",
    ctaHref: "/download",
    popular: false,
    costNote: "No credit card required",
  },
  {
    id: "pay-per-result",
    name: "Pay-Per-Result",
    subtitle: "Outcome-Based",
    badge: "Most Flexible",
    price: null,
    priceMonthly: null,
    customPrice: "$0.50",
    customPriceUnit: "per success",
    description: "Pay only for successful automations - failed ones are FREE",
    features: [
      "✓ Only pay for successful automations",
      "✓ Failed automations are FREE",
      "✓ All 20+ AI employees unlocked",
      "✓ Unlimited marketplace access",
      "✓ Real-time cost tracking",
      "✓ Transparent itemized invoicing",
      "✓ Priority support",
      "✓ All advanced features",
      "✓ Cancel anytime, no commitment",
    ],
    cta: "Try Pay-Per-Result",
    ctaHref: "/download",
    popular: true,
    costNote: "Average $25-35/month for typical usage",
  },
  {
    id: "pro",
    name: "Pro Unlimited",
    subtitle: "Best Value",
    badge: "Most Popular",
    price: 39,
    priceMonthly: 39,
    customPrice: "$39",
    customPriceUnit: "/month",
    description: "Unlimited automations at a fixed monthly price",
    features: [
      "✓ UNLIMITED automations",
      "✓ All 20+ AI employees",
      "✓ Priority support",
      "✓ Advanced analytics & reporting",
      "✓ Workflow sharing & collaboration",
      "✓ Custom AI employee training",
      "✓ Messaging platform integrations",
      "✓ API access for external triggers",
      "✓ Cancel anytime",
    ],
    cta: "Go Pro",
    ctaHref: "/download",
    popular: false,
    costNote: "Best for teams running 80+ automations/month",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    subtitle: "For Organizations",
    badge: "ROI Guarantee",
    price: null,
    priceMonthly: null,
    description: "Custom pricing with guaranteed ROI or money back",
    features: [
      "✓ Everything in Pro",
      "✓ ROI Guarantee (refund if not met)",
      "✓ Dedicated success manager",
      "✓ Custom AI employee development",
      "✓ SSO/SAML authentication",
      "✓ On-premise deployment option",
      "✓ 99.9% uptime SLA",
      "✓ Priority feature development",
      "✓ Team training & onboarding",
    ],
    cta: "Contact Sales",
    ctaHref: "/contact?plan=enterprise",
    popular: false,
    costNote: "Custom pricing with ROI guarantees",
  },
]

export type PricingTier = typeof pricingTiers[number]
